# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# set timeout for fastlane to resolve dependencies
# ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "600"

default_platform(:ios)

platform :ios do

    api_key = app_store_connect_api_key(
      key_id: "HKWV3JPTKS",
      issuer_id: "69a6de90-6029-47e3-e053-5b8c7c11a4d1",
      key_filepath: "./AuthKey_HKWV3JPTKS.p8",
      duration: 1200, # optional (maximum 1200)
      in_house: false # optional but may be required if using match/sigh
    )

  lane :build do
    # run tests
    scan

    # prepare signing certificates
    cert

    # prepare provisioning profile
    sigh

    # build, sign and package
    gym
  end

  # Upload to TestFlight
  lane :alpha do
    build
    
    pilot(api_key: api_key)
    
    increment_build_number
  end
  
  # Submit for review
  lane :release do
    build
    
  # by default deliver will call precheck and warn you of any problems
  # if you want precheck to halt submitting to app review, you can pass
  # precheck_default_rule_level: :error
  deliver(
    precheck_default_rule_level: :error,
    # Precheck cannot check In-app purchases with the App Store Connect API Key (yet).
    precheck_include_in_app_purchases: false,
    api_key: api_key
  )
    
    increment_build_number
  end
  
  # run precheck alone
  lane :check_metadata do
    precheck
  end

  lane :beta do
    build_app(scheme: "CI")
  end
  
  desc "Overlay the app icon with build information"
  lane :overlay_icon do
    # retrieve the current build number
    build_number = get_build_number
    
    # get the current app marketing version
    version_number = get_version_number
    
    # update the app icon with an overlay that shows the app version and build number across the bottom
    version_icon(
      appiconset_path: "Maximatica/Assets.xcassets/AppIcon.appiconset",
      text: "beta: #{version_number} (#{build_number})"
    )
  end

end
